### ISSUE TITLE
ThePoser broken in IE  standards mode

### ISSUE THREAD

**Issue by jsincioco** [mantisbt-plugins/ThePoser#8]
Maybe due to how IE blocks HTML Transitional pages, ThePoser is broken (excluding setting the logo). In compatibility view ThePoser works fine, but I can't set it to users since the server also has other sites that needs to implement standards view. Any thoughts on how I can improve this? (other than removing transitional declarations on every php page)

I'm using IE Edge (11.0.9600.17358)

**Comment by snowyurik** [comment]
Sorry.. can't reproduce this. Why do you use IE?

**Comment by jsincioco** [comment]
Console logs an invalid DOCTYPE error, which in turns disables XHTML
Transitional. Maybe related to this mode, this disables PHP files to
be rendered as CSS (which was supplied by ThePoser as CSS overrides).
You can see that on the attached screenshot.

I'm using this on IE because my boss loves it right now and she was
wondering why it looks "different" on that browser.

**Comment by snowyurik** [comment]
Look, this in opensource, right? I'm not big fan of Stollman, but..
If you will order a commercial website from us - this is different thing, if you want to pay for ie support we can do it. But ThePoser is freeware. This is our small contribution for opensource community to change the world and make it better.

If less people will use IE - world will be better, right? Right. 
Maybe this will force Microsoft to respect W3 standarts and RFCs, maybe not. But if more people will use browsers who follow the standarts - it will be good. Less work for us as web developers in long term. 5 years ago IE had more than half of the market and it was real pain. This is huge success for us as the community that now IE have less than 5% (4.75% according to this http://vihv.org/index.php?e=Stats). But i belive it should be zero, or Microsoft should start to respect w3.

So, if i'll fix this IE specific bug world won't become better and we won't reach our goal.

If you disagree - you are free to fork ThePoser, make the changes yourself and send me pull request. If this change won't harm behaviour of the other browsers - it will be merget into main branch. I'm against it. Personally, I do not want ThePoser to work with IE at all. But I respect your future contribution, because this is important rule of the game.

This is my official answer, you can forward it to your boss.
